### ISSUE TITLE
Bug report copy *.svg files from the doc tree

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/app4triqs#5]
Dear Nils,

When building the docs please also copy *.svg files into the doc tree. I added this manually to the CMake of TRIQS/cthyb but it seems to have disappeared since now the tutorials based on jupyter notebooks (that have svg figures) are missing the figures, again. Please see

https://triqs.github.io/cthyb/2.1.x/guide/perturbation_order_notebook.html

could you please add *.svg in the pattern for files that are copied in the doc build in app4triqs?

Best, Hugo

**Comment by Wentzell** [comment]
This is fixed with commit bb3eb8e

**Comment by HugoStrand** [comment]
Dear Nils, Thank you for the quick fix! Cheers, Hugo
